# This is a basic workflow to help you get started with Actions

name: manual-input-workflow 

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to great'
        default: 'World'
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  great:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a single command using the runners shell
      - name: Send greeting
        run: echo "Hello ${{ github.event.inputs.name }}"
